export const BEGIN_AJAX_CALL       = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR       = 'AJAX_CALL_ERROR';

export const GET_COURSES_SUCCESS   = 'GET_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS  = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const GET_USER_SUCCESS      = 'GET_USER_SUCCESS';
export const GET_LOOKUPS_SUCCESS   = 'GET_LOOKUPS_SUCCESS';

export const UPDATE_MONKEY         = 'UPDATE_MONKEY';
