//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAR.Originations.MRC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationLink()
        {
            this.ServiceLinks = new HashSet<ServiceLink>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ApplicationGroupId { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string AppTypeCode { get; set; }
    
        public virtual ApplicationGroup ApplicationGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceLink> ServiceLinks { get; set; }
        public virtual ApplicationType ApplicationType { get; set; }
    }
}
