//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAR.Originations.MRC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDemo
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Title { get; set; }
        public string WatchHref { get; set; }
        public string AuthorId { get; set; }
        public string Length { get; set; }
        public string Category { get; set; }
    }
}
